version: '3.8'

services:

  weather_back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - '8000:8000'
    networks:
      - weather_net
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - weather_net
    ports:
      - '5434:5432'


networks:
    weather_net:
      driver: bridge

volumes:
    postgres-data: